# Generated by Django 5.2.7 on 2025-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-available", "name"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/img/img.png",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
