# Generated by Django 5.2.7 on 2025-11-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-stock", "name"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
    ]
